theme: jekyll-theme-slate

title: California Marine Protected Areas Human Uses
description: Establishing a Statewide Baseline and Long-Term MPA Monitoring Program for Commercial and Commercial Passenger Fishing Vessel (CPFV) Fisheries in the State of California

show_downloads: false
